nodeLinker: "node-modules"
cacheFolder: "./.runtime/cache/yarn"
deferredVersionFolder: "./.runtime/yarn/versions"
installStatePath: "./.runtime/yarn/install-state.gz"
patchFolder: "./.runtime/yarn/patches"
pnpUnpluggedFolder: "./.runtime/yarn/unplugged"
virtualFolder: "./.runtime/yarn/__virtual__"
