version: "3"

# Only for development purposes

services:
  nginx:
    volumes:
      - ./.docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./.data/ssl:/etc/nginx/ssl:ro

  nodejs:
    command: sh -c "npm install && npm run dev"
