version: "3"

services:
  php:
    container_name: deserve_php
    build: ./docker/php-fpm
    volumes:
      - .:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    ports:
      - 9000:9000

  apache:
    container_name: deserve_apache
    build: ./docker/apache
    volumes:
      - .:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    ports:
      - 80:80
      - 443:443
    links:
      - php

  mariadb:
    container_name: deserve_mariadb
    image: mariadb:latest
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306

  nodejs:
    container_name: deserve_nodejs
    image: node:17-alpine3.14
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    ports:
      - 3000:3000
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: /bin/sh -c "npm install && npm run dev"
