version: "3"

# For production purposes

networks:
  proxy-manager:
    driver: bridge
    name: nginx-proxy-manager
    external: true

services:
  php:
    restart: unless-stopped

  queue:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    volumes:
      - ./.docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-manager
      - default

  mariadb:
    restart: unless-stopped

  nodejs:
    restart: unless-stopped
    command: sh -c "npm ci && npm run start"
