name: deserve-site

services:
  php:
    build: ./php
    volumes:
      - ../:/app
      - ../.runtime/cache/composer:/.composer/cache
    working_dir: /app
    user: $USER_ID:$GROUP_ID
    depends_on:
      - redis

  cron:
    build: ./cron
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - redis

  queue:
    build: ./php
    volumes:
      - ../:/app
    working_dir: /app

  nginx:
    image: nginx:alpine
    volumes:
      - ../:/app:ro
    working_dir: /app
    depends_on:
      - php
    networks:
      default:
        aliases:
          - api.nginx

  redis:
    image: redis:7.0.9-alpine3.17
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
