name: Deploy application

on:
  push:
    branches:
      - master

env:
  DEPLOY_PATH: /home/${{ secrets.DEPLOY_SERVER_USERNAME }}/domains/alt.deserve.ru

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Install npm dependencies
      #   run: |
      #     cd ./frontend
      #     npm ci

      # - name: Compile front
      #   run: |
      #     cd ./frontend
      #     npm run generate

      - name: Copy static content via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -azr --delete --include "public/***" --exclude "*"
          remote_path: ${{ env.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_SERVER_HOST }}
          remote_user: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_SERVER_KEY }}
